name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull the Docker Image for the Build Environment
        run: docker pull clux/muslrust
      - name: Build using the Docker Image
        run: docker container run -v "${PWD}":/volume --rm -t clux/muslrust cargo build
      - name: Run tests using the Docker Image
        run: docker container run -v "${PWD}":/volume --rm -t clux/muslrust cargo test

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull the Docker Image for the Build Environment
        run: docker pull clux/muslrust
      - name: Build using the Docker Image
        run: docker container run -v "${PWD}":/volume --rm -t clux/muslrust cargo build --release
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: "./Dockerfile"
          tags: rishit/reservoir-sampling:latest, rishit/reservoir-sampling:0.0.1
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
