name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Adding cross-compiling target Linux-musl
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build
        run: cargo build --verbose --target=x86_64-unknown-linux-musl
      - name: Run tests
        run: cargo test --verbose --target=x86_64-unknown-linux-musl

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Adding cross-compiling target Linux-musl
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build
        run: cargo build --verbose --release --target=x86_64-unknown-linux-musl
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ls
        run: ls -l ./target/
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: "./Dockerfile"
          tags: rishit/reservoir-sampling:latest, rishit/reservoir-sampling:0.0.1
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
